# Generated by Django 6.0.6 on 2026-06-23 20:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название мероприятия')),
                ('event_date', models.DateField(verbose_name='День мероприятия')),
                ('started_at', models.TimeField(verbose_name='Время начала мероприятия')),
                ('ended_at', models.TimeField(verbose_name='Время окончания мероприятия')),
            ],
            options={
                'verbose_name': 'Мероприятие',
                'verbose_name_plural': 'Мероприятия',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tg_id', models.IntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=255, verbose_name='Username')),
                ('user_role', models.CharField(choices=[('guest', 'Гость'), ('speaker', 'Спикер')], default='guest', max_length=255, verbose_name='Роль пользователя')),
                ('name', models.CharField(blank=True, max_length=255, verbose_name='Имя')),
                ('company', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('position', models.CharField(blank=True, max_length=200, verbose_name='Должность')),
                ('about', models.TextField(blank=True, verbose_name='О себе')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='SpeakerSpeech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=255, verbose_name='Тема доклада')),
                ('started_at', models.TimeField(verbose_name='Время начала выступления')),
                ('ended_at', models.TimeField(verbose_name='Время окончания выступления')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.event', verbose_name='Мероприятие')),
                ('speaker', models.ForeignKey(limit_choices_to={'user_role': 'speaker'}, on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Спикер')),
            ],
            options={
                'verbose_name': 'Выступление спикера',
                'verbose_name_plural': 'Выступления спикеров',
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания подписки')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Подписка на следующие мероприятия',
                'verbose_name_plural': 'Подписки на следующие мероприятия',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст вопроса')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время создания')),
                ('speaker_speech', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.speakerspeech', verbose_name='Выступление')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Автор вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время доната')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.event', verbose_name='Мероприятие')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meetup_core.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Донат',
                'verbose_name_plural': 'Донаты',
            },
        ),
    ]
