# Generated by Django 6.0.6 on 2026-06-25 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_core', '0002_broadcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='speakerspeech',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Состояние активности выступления'),
        ),
    ]
