# Generated by Django 6.0.6 on 2026-06-25 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meetup_core', '0003_speakerspeech_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_questionnaire',
            field=models.BooleanField(default=False, verbose_name='Заполнил анкету для знакомств'),
        ),
    ]
